version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tyb-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_PATH: /app/tyb.db
    volumes:
      - ./backend/tyb.db:/app/tyb.db
    ports:
      - "8001:8001"
    networks:
      - tyb-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tyb-frontend
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - backend
    networks:
      - tyb-net

networks:
  tyb-net:
    driver: bridge
