version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tyb-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_PATH: /app/tyb.db
    volumes:
      - ./backend/tyb.db:/app/tyb.db
    ports:
      - "8001:8001"
    networks:
      - tyb-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tyb-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://api.trackyourbest.net"

      NEXT_PUBLIC_AUTH_ME: "/auth/me"
      NEXT_PUBLIC_AUTH_LOGOUT: "/auth/logout"
      NEXT_PUBLIC_DEFAULT_DEVICE: "tyb01"

      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: "6Lf3_CQsAAAAAP04BUhHJGsDLpAhWUh0ryKV0us7"
    ports:
      - "3003:3003"
    depends_on:
      - backend
    networks:
      - tyb-net

networks:
  tyb-net:
    driver: bridge
